language: cpp
sudo: false
compiler:
  - g++

script:
  - mkdir build
  - cd build
  - cmake ..
  - make all

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - libboost-dev
    - libeigen3-dev

notifications:
  email: benjamin.lefaudeux@gmail.com
